# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 129edd451d95ffe19fb333d85403fc1cf797da289a1d87c89b153fddb56ee80576feb2c1aeefbaf479d0b1ab8446dc389fe65242397424d5d511ec5954afdcd4

test:
  secret_key_base: 99aed24b4527a2b002038c748eb92fb60c4790b07f2634fb13c2156506fd5143fbee0c2ad580a0a3e58ddb3d1e5c021c7fc0fca1ae3ca1933b722f659c76fb4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
